Repository intel-retail/performance-tools, pull requests merged in 2024-11, with the labels that each got.

#70 fix: fix the defect about the device card id issue in igt script for NUC system
  docker/intel-top/entrypoint.sh
Labels: bug, 3.2

#71 fix: fix python3 syntax error and added some missing dependency packages for running make consolidate
  benchmark-scripts/Makefile
  benchmark-scripts/benchmark.py
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
  benchmark-scripts/requirements.txt
Labels: bug, 3.2

#69 feat: update github actions
  .github/workflows/build.yaml
  .github/workflows/trivy-scan.yaml
  .github/workflows/trivyimagescan.yaml
Labels: enhancement

#72 feat: enhance stream-density mode for the benchmark script to take multiple target_fps and container_names
  benchmark-scripts/Makefile
  benchmark-scripts/benchmark.py
  benchmark-scripts/stream_density.py
  benchmark-scripts/stream_density_test.py
Labels: enhancement, 3.2

#75 feat: update jobs version to avoid deprecation
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/reports.yaml
  .github/workflows/reviewdog.yaml
  .github/workflows/scorecard.yml
  .github/workflows/trivy-scan.yaml
  .github/workflows/trivyimagescan.yaml
Labels: enhancement
