Repository intel-retail/performance-tools, pull requests merged in 2024-04, with the labels that each got.

#37 feat: add docstring comments to the benchmark script
  benchmark-scripts/benchmark.py
Labels: documentation, enhancement, 3.0

#38 Results format
  benchmark-scripts/Makefile
  benchmark-scripts/benchmark.py
  benchmark-scripts/benchmark_integration.py
  benchmark-scripts/benchmark_test.py
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
  benchmark-scripts/test_csv/test.csv
  docker/intel-top/Dockerfile
  docker/intel-top/entrypoint.sh
Labels: enhancement, 3.0

#39 fix: update default path for git submodule
  benchmark-scripts/benchmark.py
Labels: enhancement, 3.0

#41 Cleanup benchmark script dir
  Makefile
  benchmark-scripts/Makefile
  benchmark-scripts/benchmark.sh
  benchmark-scripts/benchmark_integration.py
  benchmark-scripts/camera-simulator.sh
  benchmark-scripts/cleanup_gpu_metrics.sh
  benchmark-scripts/copy-platform-metrics.sh
  benchmark-scripts/download_sample_videos.sh
  benchmark-scripts/format_avc_mp4.sh
  benchmark-scripts/get-gpu-info.sh
  benchmark-scripts/log_time_monitor.sh
  benchmark-scripts/smoke_test.sh
  benchmark-scripts/smoke_test_benchmark.sh
  benchmark-scripts/stop_server.sh
  benchmark-scripts/test_benchmark_multiple_pipelines.sh
  benchmark-scripts/test_format_avc_mp4.sh
  benchmark-scripts/test_src/docker-compose.yml
  benchmark-scripts/test_src/test.csv
  benchmark-scripts/test_stream_density.sh
Labels: enhancement

#43 feat: implement stream density python
  .gitignore
  benchmark-scripts/Makefile
  benchmark-scripts/benchmark.py
  benchmark-scripts/stream_density.py
  benchmark-scripts/stream_density_test.py
  benchmark-scripts/test_stream_density_results/gst-launch_20240405141414071831277_gst.log
  benchmark-scripts/test_stream_density_results/gst-launch_20240405141713198120407_gst.log
  benchmark-scripts/test_stream_density_results/pipeline20240405141414071831277_gst.log
  benchmark-scripts/test_stream_density_results/pipeline20240405141713198120407_gst.log
  benchmark-scripts/test_stream_density_results/r20240405141414071831277_gst.jsonl
  benchmark-scripts/test_stream_density_results/r20240405141713198120407_gst.jsonl
Labels: 3.0

#44 fix: Include sample media download scripts with performance tools
  benchmark-scripts/download_sample_videos.sh
  benchmark-scripts/format_avc_mp4.sh
Labels: enhancement, 3.0
