Repository intel-retail/performance-tools, pull requests merged in 2025-04, with the labels that each got.

#106 fix: sdl dependency issues
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/projectsSync.yaml
  .github/workflows/reports.yaml
  .github/workflows/requirements.txt
  .github/workflows/reviewdog.yaml
  .github/workflows/scorecard.yml
  .github/workflows/trivy-scan.yaml
  .github/workflows/trivyimagescan.yaml
  docker/intel-top/Dockerfile
  docker/platform/Dockerfile
  docker/platform/requirements.txt
  docker/xpum/Dockerfile
  docker/xpum/requirements.txt
  helm/intel-top/Dockerfile
  helm/platform/Dockerfile
  helm/platform/requirements.txt
  helm/xpum/Dockerfile
  helm/xpum/requirements.txt
Labels: bug, cicd, security

#107 fix: hash for actions/checkout@v4
  .github/workflows/scorecard.yml
Labels: bug, cicd, security

#108 fix: adding more hashes
  .github/workflows/reports.yaml
  .github/workflows/reviewdog.yaml
  .github/workflows/scorecard.yml
Labels: bug, cicd, security

#109 feat: create npu collection utility in python
  docker/docker-compose.yaml
  docker/npu-util/npu_logger.py
Labels: enhancement

#110 add: openssf best practices badge
  README.md
Labels: documentation, security

#113 fix: Small fixes
  benchmark-scripts/benchmark.py
  benchmark-scripts/consolidate_multiple_run_of_metrics.py
Labels: bug
